### ISSUE TITLE
DG Review (by TA)

### ISSUE THREAD

**Issue by Leeyp** [AY2122S1-CS2113T-F11-3/tp#120]
Please fix the images in your DG, as it cannot be viewed on the DG page. 
![image](https://user-images.githubusercontent.com/2010527/139518663-a2b46ad5-8adb-4d40-91c3-b778a4ee93b8.png)

Please be careful when generating the sequence diagrams. Observed several bugs (there might be more that I have failed to identify), for example:
![image](https://user-images.githubusercontent.com/2010527/139518693-35a0d71b-3985-43ba-ba01-6311f01fcd03.png)
1. Objects should have a colon for entities. It is missing from ClientPackageList
2. Return arrow should be at the bottom of the activation bar instead of in the middle (there should not be gap)
3. Constructor arrow should be at the top of the activation bar and not on the entity name.

Please note that these "syntax" issues related to sequence diagrams are easier to identify, and therefore can be potential penalties if flagged by other students during peer review.

In another example (although these bugs are "harder" to spot and so would be unlikely to be flagged by your peers, but might be flagged by Prof): 
![image](https://user-images.githubusercontent.com/2010527/139518804-44ed036c-2754-47f3-9078-7208d8012b19.png)
1. calls for FindClientCommand -> the entity should be FindClientCommand rather than Command
2. from command to client list --- dunno what is the call abt, nothing mentioned, but it returns 3 things, how? is it an object?

The above findings are not exhaustive, I observed repeated errors in other diagrams as well, please perform a double check through your UG/DG when you have time to ensure that potential errors are fixed.

While these errors exist in the DG and need to be fixed, in general your team is on the right track. Please keep up the good work and be careful to keep your UG/DG foolproof to avoid criticism during peer review.

**Comment by Bobowoo2468** [comment]
Thanks for the advice YP
