### ISSUE TITLE
[PE-D] invalid email format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-3/tp#129]
I type in invalid email format but the system consider it correct and store it
![bug4.png](https://raw.githubusercontent.com/Cuiminjing/ped/main/files/e9beb0fe-db78-4bac-b577-d8aa2fb963c5.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Cuiminjing/ped#4

**Comment by Bobowoo2468** [comment]
This invalid email format will be allowed as an entry, but a warning will be thrown.
