### ISSUE TITLE
[PE-D] add -p command 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-3/tp#130]
A flight can be added to 2 tours so for one flight may have 2 different price and name

![bug5.png](https://raw.githubusercontent.com/Cuiminjing/ped/main/files/db66a2cb-1ff1-4869-9fa3-cad15b0c2854.png)
![bug51.png](https://raw.githubusercontent.com/Cuiminjing/ped/main/files/1c549340-7628-4e86-b018-2244e462bec9.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Cuiminjing/ped#5

**Comment by Bobowoo2468** [comment]
The price is for the tour, the flight can be the same.
