### ISSUE TITLE
[PE-D] date format(extended)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-3/tp#133]
the function of add date part is not complete because I can add an extended date 31/2/2022,.

![bug6.png](https://raw.githubusercontent.com/Cuiminjing/ped/main/files/d2bc0e30-35ab-4312-9445-b0a348c94d5d.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Cuiminjing/ped#6

**Comment by Bobowoo2468** [comment]
There's is no 31 Feb
