### ISSUE TITLE
[PE-D] Able to add invalid times and dates

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-3/tp#145]
![Screenshot 2021-10-29 170752.png](https://raw.githubusercontent.com/JWweiyin/ped/main/files/319be1e7-430e-4482-b23a-a6f2df0f7e53.png)

The program probably shouldn't allow the user to input incorrect times and dates like 13:65 or 32/13/21. Perhaps an exception can be thrown for that.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JWweiyin/ped#4

**Comment by Bobowoo2468** [comment]
Date time parsing has been cleared, exception will be thrown.
