### ISSUE TITLE
[PE-D] invalid contact number format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F11-3/tp#149]
The wrong format of contact number(00000000) is accepted by the system
![QQ图片20211029172100.png](https://raw.githubusercontent.com/Cuiminjing/ped/main/files/b8d34865-29e9-4458-8d5c-070ebace24e8.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Cuiminjing/ped#12

**Comment by Bobowoo2468** [comment]
We feel that such erroneous contact number can be entered, but there should be a warning for this erroneous input.
